### ISSUE TITLE
cudnn error in nn-classification

### ISSUE THREAD

**Issue by pck00** [apcamargo/genomad#54]
Hello, running into this error when running end-to-end: 

2023-11-28 12:58:38.487936: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 12:58:38.487978: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 12:58:38.487985: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
 Executing geNomad nn-classification (v1.7.1). This will classify the input sequences into chromosome, plasmid, or virus based on the nucleotide    │
│  sequence.                                                                                                                                          │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│  Outputs:                                                                                                                                           │
│    ecortotal_relax/total_nn_classification                                                                                                          │
│    ├── total_nn_classification.json (execution parameters)                                                                                          │
│    ├── total_encoded_sequences (directory containing encoded sequence data)                                                                         │
│    ├── total_nn_classification.tsv (contig classification: tabular format)                                                                          │
│    ├── total_nn_classification.npz (contig classification: binary format)                                                                           │
│    ├── total_encoded_proviruses (directory containing encoded sequence data)                                                                        │
│    ├── total_provirus_nn_classification.tsv (provirus classification: tabular format)                                                               │
│    └── total_provirus_nn_classification.npz (provirus classification: binary format)                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[12:58:41] Executing genomad nn-classification.
[12:58:41] Previous execution detected. Steps will be skipped unless their outputs are not found. Use the --restart option to force the execution of all the steps again.
[12:58:41] total_encoded_sequences was found. Skipping sequence encoding.
[12:58:41] total_encoded_proviruses was found. Skipping provirus encoding.
Classifying sequences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0% | -:--:--error: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/pck/anaconda3/envs/genomad/bin/genomad", line 10, in <module>
    sys.exit(cli())
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1276, in end_to_end
    ctx.invoke(
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 719, in nn_classification
    genomad.nn_classification.main(
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/modules/nn_classification.py", line 316, in main
    contig_predictions.append(nn_model.predict(batch, verbose=0))
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node model_1/model/batch_normalization/batchnorm/Rsqrt defined at (most recent call last):
  File "/home/pck/anaconda3/envs/genomad/bin/genomad", line 10, in <module>

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1157, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1688, in invoke

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 1434, in invoke

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 1276, in end_to_end

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/click/core.py", line 783, in invoke

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/cli.py", line 719, in nn_classification

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/genomad/modules/nn_classification.py", line 316, in main

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 2631, in predict

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 2416, in predict_function

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 2401, in step_function

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 2389, in run_step

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 2357, in predict_step

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 589, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/functional.py", line 515, in call

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/functional.py", line 672, in _run_internal_graph

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/training.py", line 589, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/functional.py", line 515, in call

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/functional.py", line 672, in _run_internal_graph

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/home/pck/anaconda3/envs/genomad/lib/python3.10/site-packages/keras/src/layers/normalization/batch_normalization.py", line 788, in call

JIT compilation failed.
         [[{{node model_1/model/batch_normalization/batchnorm/Rsqrt}}]] [Op:__inference_predict_function_978]

This is after installing via conda, which includes the following packages that are presumably at fault:

 cuda-version       conda-forge/noarch::cuda-version-11.8-h70ddcb2_2 None
  cudatoolkit        conda-forge/linux-64::cudatoolkit-11.8.0-h4ba93d1_12 None
  cudnn              conda-forge/linux-64::cudnn-8.8.0.121-h838ba91_4 None

Looking forward to experiencing the full functionality,
cheers :)

**Comment by apcamargo** [comment]
This seems to be a problem with CUDA, not geNomad. Can you try to run geNomad after executing the command below, which will prevent TensorFlow from using CUDA.

```
export CUDA_VISIBLE_DEVICES=-1
```

**Comment by pck00** [comment]
Worked like a charm! Thanks for the quick reply

**Comment by apcamargo** [comment]
No worries!
